apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: genericattestationpolicies.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: GenericAttestationPolicy
    plural: genericattestationpolicies
    singular: genericattestationpolicy
